version: '3'

dotenv: ['.env.local','.env']

tasks:
  setup:
    cmds:
      - npm install
  dev:
    cmds:
      - npm run dev
  build:
    deps: [fix]
    cmds:
      - npm run build
  fix:
    cmds:
      - npm run lint-fix
      - npm audit fix
  deploy-prod:
    cmds:
      - aws s3 sync ./dist/ {{.S3_PROD}} --delete
  deploy-staging:
    cmds:
      - aws s3 sync ./dist/ {{.S3_STAGING}} --delete